# Generated by Django 5.0.2 on 2024-02-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=60, null=True)),
                ('mailbox', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, null=True, unique=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron_app.employee')),
            ],
        ),
    ]
