# Generated by Django 5.0.2 on 2024-03-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enron_app', '0002_alter_message_path_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='JM_id',
        ),
    ]
