# Generated by Django 5.0.2 on 2024-04-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron_app', '0003_remove_message_jm_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeetoMailadress',
            new_name='EmployeetoMailaddress',
        ),
        migrations.RenameField(
            model_name='employeetomailaddress',
            old_name='mailadress_id',
            new_name='mailaddress_id',
        ),
        migrations.AddField(
            model_name='mailadress',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='JM_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
