# Generated by Django 5.0.2 on 2024-04-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron_app', '0004_rename_employeetomailadress_employeetomailaddress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailAdress',
            new_name='MailAddress',
        ),
        migrations.RenameField(
            model_name='employeetomailaddress',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeetomailaddress',
            old_name='mailaddress_id',
            new_name='mailaddress',
        ),
        migrations.CreateModel(
            name='AddresstoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron_app.employee')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron_app.message')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeetoMessage',
        ),
    ]
