# Generated by Django 5.0.2 on 2024-04-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron_app', '0005_rename_mailadress_mailaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstomessage',
            name='mailaddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron_app.mailaddress'),
        ),
    ]
