# Generated by Django 5.0.2 on 2024-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron_app', '0006_alter_addresstomessage_mailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
