# Generated by Django 5.0.2 on 2024-05-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron_app', '0007_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('emp_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='enron_app.employee')),
                ('emp_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='enron_app.employee')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron_app.message')),
            ],
        ),
    ]
